{% set name = "darts" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/khanrc/pt.darts/archive/{{ version }}.tar.gz
  sha256: b0c4689cdabc5fdec0ba3c829057aa2cb94f9a97036cf5ae545de6247d301e9c

build:

  number: 0
  script:
    - cp -r $SRC_DIR $SP_DIR/pt.darts


requirements:
  host:
    - python

  run:
    - python

test:
  imports:
    - pt.darts


about:
  home: https://github.com/khanrc/pt.darts
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Differentiable Architecture Search
  description: |
    The algorithm is based on continuous relaxation and gradient descent in the architecture space. 
    It is able to efficiently design high-performance convolutional architectures for image classification 
    (on CIFAR-10 and ImageNet) and recurrent architectures for language modeling (on Penn Treebank and WikiText-2). 
    Only a single GPU is required.
  doc_url: https://github.com/khanrc/pt.darts
  dev_url: https://github.com/khanrc/pt.darts

extra:
  recipe-maintainers:
    - Tata17
    - oblute
